#!/bin/bash

echo "Input a subnet or IP address [default = 10.0.0.0/24]:"
echo -n "> "
read -r SUBNET_OR_IP

SUBNET_OR_IP=${SUBNET_OR_IP:-"10.0.0.0/24"}
PATH_XML="/tmp/nmap-results.xml"

echo "Scanning the subnet: $SUBNET_OR_IP"
echo "Attempting to run nmap. This may take some time depending on the scan"

if sudo nmap -sn --traceroute "$SUBNET_OR_IP" -oX=$PATH_XML > /dev/null; then
  echo "Exporting report to '$PATH_XML'"
else
  echo "Failed to run nmap"
  exit 1
fi

if ! elo $PATH_XML; then
  echo "Failed to parse XML report"
  exit 1
fi
